#!/bin/bash
# Based on Jess Frazelle's dotfiles (https://github.com/jfrazelle/dotfiles.git)

alias ls="ls --color"
alias l="ls -lF --color"
alias la="ls -A --color"
alias ll="ls -laF --color"
alias lsd="ls -lF --color | grep --color=never '^d'"

alias grep="grep --color=auto"


alias myps='ps -u $LOGNAME'
alias ]='/usr/bin/gvfs-open'
alias ]]='sudo /usr/bin/gvfs-open'
alias cft="find . -type f | sed -e 's/.*\.//' | sort | uniq -c | sort -rn"


## IP Addresses
alias pubip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="sudo ifconfig | grep -Eo 'inet (ad{1,2}r:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"
alias ips="sudo ifconfig -a | grep -Eo 'inet6?(\sad{1,2}r)?:\s?((([0-9]+.){3}[0-9]+)|[a-fA-F0-9:]+)' |
awk '{ sub(/inet6?( ad{1,2}r)?: ?/, \"\"); print }'"

# vim: filetype=sh
