#!/bin/bash
# Global functions
#open() {
#	if [[ $# -eq 0 ]]; then
#		echo "Usage: open <URL>"
#	else
#		if [[ -e /usr/bin/gvfs-open ]]; then
#			/usr/bin/gvfs-open $* > /dev/null 2>&1
#		else 
#			/usr/bin/gnome-open $* > /dev/null 2>&1
#		fi
#	fi
#}

# Get gitignore template from gitignore.io
function gi() {
    curl -sL https://www.gitignore.io/api/$@
}
# vim: ft=sh
