#!/bin/bash
# Global functions
#open() {
#	if [[ $# -eq 0 ]]; then
#		echo "Usage: open <URL>"
#	else
#		if [[ -e /usr/bin/gvfs-open ]]; then
#			/usr/bin/gvfs-open $* > /dev/null 2>&1
#		else
#			/usr/bin/gnome-open $* > /dev/null 2>&1
#		fi
#	fi
#}

# Get gitignore template from gitignore.io
function gi() {
    curl -sL https://www.gitignore.io/api/$@
}

SSH_ENV="$HOME/.ssh/environment"
function start_agent {
    echo "Initialising new SSH agent..."
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add;
}

# Source SSH settings, if applicable

if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    #ps ${SSH_AGENT_PID} doesn't work under cywgin
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi
# vim: ft=sh
