#!/usr/bin/env sh
# Java related

# Switch Java alternative
function switch_java() {
    sudo update-alternatives --config java
    set_java_home
}

# Export JAVA_HOME relevant to the current Java alternative
function set_java_home() {
    JAVA_HOME=$(readlink -f $(which java) | sed -e 's:/bin/java::')
    export JAVA_HOME
}
# Maven Environment variables
M2_HOME=${HOME}/tools/apache-maven-3.6.3
MAVEN_HOME=${HOME}/tools/apache-maven-3.6.3
PATH=${PATH}:${M2_HOME}/bin
export M2_HOME MAVEN_HOME

set_java_home

# vim: ft=sh:
