#!/bin/bash
# Nodejs & NPM related
NVM_DIR=${HOME}/.nvm
if [ -e "${NVM_DIR}" ]; then
    export NVM_DIR
    [ -s "${NVM_DIR}/nvm.sh" ] && \. "${NVM_DIR}/nvm.sh" # This loads nvm
    [ -s "${NVM_DIR}/bash_completion" ] && \. "${NVM_DIR}/bash_completion" # This loads bash completion
else
    export NPM_PREFIX=${HOME}/.local
    NPM_VER=$(command -v npm)
    if [ ! -z "${NPM_VER}" ]; then
        command npm config set prefix ${NPM_PREFIX} --no-update-notifier
    else
        echo "NPM is not installed."
    fi
fi

# Unset manpath so we can inherit from /etc/manpath via the `manpath`
# command
unset MANPATH  # delete if you already modified MANPATH elsewhere in your config
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"
# vim:ft=sh
