#!/bin/bash
# Python related
# Instruct Pyenv to generate shared libraries
# Seems necessary for YouCompleteMe plugin.
PYTHON_CONFIGURE_OPTS="--enable-shared"

PYENV_HOME=${HOME}/.pyenv
if [ -e "${PYENV_HOME}/bin" ]; then
    export PATH="${PYENV_HOME}/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
else
    echo "Pyenv not installed."
fi

DEPHELL_CPM="${HOME}/.local/etc/bash_completion.d/dephell.bash-completion"
if [ -e ${DEPHELL_CPM} ]; then
    source ${DEPHELL_CPM}
fi


# vim:ft=sh
